name: network_delay_dart
description: A Dart project to calculate network delay time using Dijkstra's algorithm.
version: 1.0.0

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  collection: ^1.19.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
